---
- name: Install, Configure, Upgrade Matomo
  hosts: web
  become: yes

  tasks:
    - name: Make sure required packages are installed
      apt:
        pkg:
          - apache2
          - libapache2-mod-php7.2
          - unzip
          - php7.2-mbstring
          - php7.2-mysql
          - php7.2-xml
          - php7.2-gd
        state: present
        update_cache: yes
      # save output into a variable so we can check it in the next task
      register: installation

    - name: Restart webserver if installation changed
      service:
        name: apache2
        state: restarted
      # only run when (if) packages were installed in the previous step
      when: installation is changed

    - name: Make sure Matomo files are present
      unarchive:
        src: "files/matomo.zip"
        dest: "{{ webroot }}"
        owner: www-data
        group: www-data
        exclude:
          - How to install Matomo.html

    - name: Make sure Matomo is configured correctly
      template:
        src: templates/webroot/matomo/config/config.ini.php.j2
        dest: "{{ webroot }}/matomo/config/config.ini.php"
        owner: www-data
        group: www-data
